live_config_reload = true

[window]

startup_mode = "Maximized"
option_as_alt = "Both"

[scrolling]

history = 50000

[font]

normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Regular Italic" }

size = 12
