
format = """
$username\
$hostname\
$directory\
$git_branch\
$nix_shell\
$line_break\
$cmd_duration\
$character\
"""
right_format = """$kubernetes"""
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true



# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[aws]
disabled = true

[directory]
truncation_length = 1

[docker_context]
disabled = true

[nix_shell]
format = '$symbol'



[kubernetes]
format = '[⛵$context \($namespace\)](dimmed green) '
disabled = false
[[kubernetes.contexts]]
context_pattern = "staging.scripbox.org"
context_alias = "staging"
[[kubernetes.contexts]]
context_pattern = "ap-south-1-production.scripbox.net"
context_alias = "prod"
[[kubernetes.contexts]]
context_pattern = "docker-desktop"
context_alias = "local"

